### ISSUE TITLE
compatibility with other brokers

### ISSUE THREAD

**Issue by kabaluyot** [edusperoni/nativescript-mqtt#1]
does this work with cloudmqtt rbroker with these port configs?
![image](https://user-images.githubusercontent.com/38805756/48963083-79c02a00-efc6-11e8-87b5-e40635bf0fbe.png)

**Comment by edusperoni** [comment]
If it's over websockets, it should work.

You can try it yourself like this:
- clone this repo
- edit these connection parameters: https://github.com/edusperoni/nativescript-mqtt/blob/master/demo/app/main-view-model.ts#L11-L17
- `useSSL: true` and `port: 30811`
- Put the username and password in the connect method: https://github.com/edusperoni/nativescript-mqtt/blob/master/demo/app/main-view-model.ts#L42
- `cd src/ && npm install && npm run demo.android`
- check if it connects successfully

**Comment by kabaluyot** [comment]
I'll update you

**Comment by kabaluyot** [comment]
By the way, a hugeeee thank you for keeping this plugin alive again :)

**Comment by edusperoni** [comment]
You're welcome :)

I was actually maintaining it in my own fork before, so this will actually be less work in the long term, haha

**Comment by kabaluyot** [comment]
I was about to switch back to java because of outdated plugins. Im new to nativescript :)

**Comment by kabaluyot** [comment]
Confirmed. It work with cloudmqtt via TLS
![image](https://user-images.githubusercontent.com/38805756/48963367-bc383580-efcb-11e8-8bbf-f12fd77969d1.png)

Hopefully I can make it work in ns-vue-ts

**Comment by edusperoni** [comment]
Awesome! I'm sure it can work with ns-vue-ts!

**Comment by kabaluyot** [comment]
you're awesome
