### ISSUE TITLE
Using it in Web-based Apps (Nuxt, Vue)

### ISSUE THREAD

**Issue by kabaluyot** [edusperoni/nativescript-mqtt#12]
This is a question regarding the package is compatible with web-based applications considering that this is all based on paho-mqtt.js. Currently, there is no maintained vue-mqtt package out there and I tried this library in TNS, maybe it can work for web-based MQTT.

**Comment by edusperoni** [comment]
This is just an abstraction over paho-mqtt. It should work provided you use the default version of `paho-mqtt` instead of the one provided
