### ISSUE TITLE
Connection issue with V3 on iOS

### ISSUE THREAD

**Issue by kryptus36** [edusperoni/nativescript-mqtt#16]
### Which platform(s) does your issue occur on?
- iOS, both emulator and physical device. Works on Android.
### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)

7.0.10

"dependencies": {
    "@nativescript-community/ui-pager": "^13.0.0-alpha.10",
    "@nativescript/appversion": "^2.0.0",
    "@nativescript/core": "~7.0.10",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "^3.0.0",
    "@types/node": "^12.12.7",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.28",
    "nativescript-audio-player": "^1.0.3",
    "nativescript-insomnia": "^2.0.0",
    "nativescript-mqtt": "^3.0.0",
    "nativescript-ui-listview": "^9.0.2",
    "nativescript-ui-sidedrawer": "^9.0.3"
  },
  "devDependencies": {
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.1",
    "@nativescript/types": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "node-sass": "^4.14.1",
    "tslint": "^6.1.1",
    "typescript": "3.9.7"
  },

I'm getting this error from onConnectionFailure:

{
"errorCode": 16,
"errorMessage": "AMQJS0016E Invalid MQTT message type 0."
}

Google suggests react native once had a similar issue caused by converting to utf8 instead of base64. I can't find much in the way of what the error actually means.

**Comment by edusperoni** [comment]
This is an issue with nativescript-websockets. I've opened a PR for it. You can manually patch it on your node_modules to test if you want

**Comment by kryptus36** [comment]
Looks like he just merged it. I'll give it a try.

**Comment by kryptus36** [comment]
yes, fixed. Thanks for all your help!

**Comment by edusperoni** [comment]
@kryptus36 I'm releasing a new version soon with a monkey patch until `nativescript-websockets` is updated and I can update the dependency version

**Comment by kryptus36** [comment]
@edusperoni this just came back to bite me. Any chance you can put out a 3.0.2 version that updates the websocket dependency to 1.5.6 so it doesn't break when I do a reinstall?
