### ISSUE TITLE
Typescript error for Message (onMessageArrived)

### ISSUE THREAD

**Issue by kabaluyot** [edusperoni/nativescript-mqtt#3]
I followed the angular template using vue-template-ts and I got this error

![image](https://user-images.githubusercontent.com/38805756/48963154-ae80b100-efc7-11e8-9e1a-1b2369b7b8f3.png)

**Comment by edusperoni** [comment]
Since message can be undefined, you can use `.on((message?: Message) => {`

**Comment by kabaluyot** [comment]
Can I little help with TS?  :), 
![image](https://user-images.githubusercontent.com/38805756/48963476-133f0a00-efce-11e8-8cd3-3bb5475f8c00.png)
It says Object is possibly undefined

**Comment by edusperoni** [comment]
you can use:

```
if (message) {
// do stuff with message
}
```
