### ISSUE TITLE
Implementation of publishing messages to broker

### ISSUE THREAD

**Issue by kabaluyot** [edusperoni/nativescript-mqtt#4]
How to publish message from app to the mqtt broker?

**Comment by edusperoni** [comment]
`mqttClient.publish(message)`

```
mqttClient.publish(new Message(new Message({
    destinationName: "topic",
    payloadString: "data to send"
}));
```

**Comment by kabaluyot** [comment]
i'll definitely try this out.. If got all this working, is it okay that I will update readme to help others? :)

**Comment by edusperoni** [comment]
Sure, you're welcome to submit a PR :)

**Comment by kabaluyot** [comment]
in the above code, I think new Message was duplicated causing the mqtt connection to close. But I got it working with this,

this.mqtt_client.publish(new Message({
                destinationName: "PubMonitor",
                payloadString: "data to send"
            }));

**Comment by kabaluyot** [comment]
I have question sir, what is the purpose of the other parameters?.. I can send to broker but I also get the message I sent which can be of course get rid of using conditionals..

![image](https://user-images.githubusercontent.com/38805756/48971196-7de55980-f051-11e8-8c03-9e408bac4dd3.png)

**Comment by edusperoni** [comment]
The first line was just showing what method to call, the code you used is correct :)

**Comment by edusperoni** [comment]
They're all part of the mqtt spec:

payloadBytes sends raw bytes instead of a string

qos: http://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels

retained: http://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages

**Comment by kabaluyot** [comment]
very much explained.. thank you <3

**Comment by DamiJegede** [comment]
Thanks @edusperoni for this amazing plugin. I struggled for days. I guess a documentation update will solve this issue for others.
